/*
 * This source file was generated by the Gradle 'init' task
 */
package exercise05;

public class App {
  public static void main(String[] args) {
    Arifmetic arifmetic = Arifmetic.readArifmetic();

    arifmetic.calcArifmetic();
    arifmetic.printArifmetic();
  }
}
