/*
 * This source file was generated by the Gradle 'init' task
 */
package exercise01;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class TriangleTest {
  @Test
  public void testValidTriangle() {
    Point point1 = new Point(1.0, 1.0);
    Point point2 = new Point(2.0, 2.0);
    Point point3 = new Point(5.0, 5.0);
    Triangle triangle = new Triangle(point1, point2, point3);
    assertEquals(11.414, triangle.getPerimeter(), 0.001);
  }

  @Test
  public void testInvalidTriangle() {
    Point point1 = new Point(2.0, 1.0);
    Point point2 = new Point(2.0, 1.0);
    Point point3 = new Point(2.0, 1.0);
    Triangle triangle = new Triangle(point1, point2, point3);
    assertNull(triangle.getPerimeter());
  }

  @Test
  public void testDegenerateTriangle() {
    Point point1 = new Point(2.0, 1.0);
    Point point2 = new Point(2.0, 1.0);
    Point point3 = new Point(3.0, 1.0);
    Triangle triangle = new Triangle(point1, point2, point3);
    assertNull(triangle.getPerimeter());
  }
}