/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "exercise00.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// plugins {
//     application
// }

// group = "com.example"
// version = "0.0.1-SNAPSHOT"

// repositories {
//     mavenCentral()
// }

// dependencies {
//     implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20")
//     testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2")
//     testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.2")
// }

// application {
//     mainClass.set("exercise00.App")
// }

// java {
//     toolchain {
//         languageVersion.set(JavaLanguageVersion.of(18))
//     }
// }